version: '3'
services:
    wokai:
        build: ./
        image: wokai:v1
        ports:
            - 3333:3333
            - 5000:5000
        container_name: wokai
        command: "node ./server/server.js"