version: '3.3'
services:
  # 服务名称
  front:
    container_name: front
    # 镜像:版本
    image: nginx:latest
    restart: always
    # 映射容器80端口到本地
    ports:
      - '3000:80'
      # - "443:443"
    # 映射本地文件到容器
    volumes:
      # 映射nginx.conf文件到容器的/etc/nginx/conf.d目录并覆盖default.conf文件
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # 映射build文件夹到容器的/usr/share/nginx/html文件夹
      - ./build:/usr/share/nginx/html
    # 覆盖容器启动后默认执行的命令。
    command: /bin/bash -c "nginx -g 'daemon off;'"
    # 依赖于api容器，被依赖容器启动后此web容器才可启动
    depends_on:
      - wokai
  wokai:
    container_name: wokai_backend
    build: ./
    # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
    restart: always
    # 映射端口
    ports:
      - "3333:3333"
      - "5000:5000"
    env_file:
      - ./.env
    # 环境变量(.env)
    # environment:
    #   - ATLAS_URI="mongodb+srv://admin:zzz123@mmwuzhi.vxx6t.mongodb.net/test-app?retryWrites=true&w=majority"
    #   - PUBLIC_VAPID_KEY="BOVjyLKO6qyyTL_EkSuANUdMFfjCIdn26dDqXLBE69RKabZ5mQF6pU-GC9YJo01o5N9EOSs6nA_K8B1DqXqeIe8"
    #   - PRIVATE_VAPID_KEY="77RcuZCSgnkNpTn-BB9mTiD_O4Gj_YTyoo2ko7Gpyds"

